README.md
The licence is unchanged (remains CC BY-SA 4.0), but the text was created with the standard licence tool at https://creativecommons.org/choose/ this time, which uses the current logo. This one is rendered better in Github.
=> use the standard licence text with the current logo

config.yaml, markdown/misc/credits/index.md, static/license.html
Das bisher verwendete [Hugo Learn Theme](https://github.com/matcornic/hugo-theme-learn) wird offenbar nicht mehr gepflegt. Mit [Hugo Relearn Theme](https://github.com/McShelby/hugo-theme-relearn) steht ein Fork zur Verfügung, der nach erster Prüfung direkt kompatibel ist und der aktiv gepflegt wird. Zusätzlich bietet das Theme verschiedene Modes an (light, dark, ...).
Siehe auch #127.
=> Switch main theme

config.yaml
usually we use headings level 2 and larger. only in compiler construction level 1 is still used in lecture-bc for the outline.
=> Hugo-config: start toc at level two (again)

Makefile
```
content/
|___  _index.md                         
|___  mypage/
|___  index.md                        
|___  images/
|___  wuppie.png
```
To reference images in `index.md` use `![](images/wuppie.png)`. This works in GH preview, and in slides and generated pages.
```
content/
|___  _index.md                         
|___  mypage.md
|___  mypage.images/
|___  wuppie.png                      
```
To reference images in `mypage.md` use `![](mypage.images/wuppie.png)`. This works in GH preview, and in slides. 
For generated pages we need to transform this to `![](../mypage.images/wuppie.png)` via Lua filter or use a (new) custom shortcode. (to be done in https://github.com/PM-Dungeon/PM-Lecture/issues/128)
---
fixes #155
=> Makefile: add slide targets for single markdown files

.github/actions/alpine-pandoc-hugo/install-packages.sh, .github/workflows/hugo.yaml, .github/workflows/slides.yaml, Makefile
- website: publish as branch `_hugo`
- website: publish .zip of website (inside `docs/`) on `_hugo` as well
- slides: publish `pdf/` as branch `_slides` instead of uploading artefacts
fixes #133
=> Workflows: publish website as .zip and pdf's as branch

Makefile
Für Single-Markdown-Pages war bisher ein spezieller Ordner `<path>/<page>.images/` im `img.html`-Shortcode fest kodiert. Nachdem mit #282 diese an sich unnötige Beschränkung aufgehoben wurde und nun gemeinsame Abbildungsordner für mehrere, auf einer Ebene liegende Lehreinheiten möglich sind, muss das auch im Makefile angepasst werden. 
Für die Abbildungen wird im `img.html`-Shortcode der `<path>` sowie der im Markdown spezifizierte relative Pfad zur Abbildung zusammengefügt. Beispiel: Für eine Single-Markdown-Page `./markdown/topic/subtopic/foo.md` wird als Pfad `topic/subtopic/` genutzt. Wenn in `foo.md` eine Abbildung `![](img/wuppie.png)` referenziert wird, resultiert das im `img.html`-Shortcode zu `topic/subtopic/img/wuppie.png`. Dies muss im Makefile für das Slide-Target (Variante …
=> Makefile: fix handling of shared image folders for single markdown files (slides)

markdown/org/grading.md
Problem: Wir haben noch zu viele offene alte Prüfungen, die dann fälschlicherweise auch mit 50:50 bewertet würden ...
=> Grading: Theorie:Praxis wieder 50:50

markdown/assignments/pool_concept/tasks/logging.md
In der ersten Aufgabe wird bei dem Punkt "Class" mit der angegeben Methode der Methodenname  aufgerufen und bei dem Punkt "Method" der Klassenname. Ich geh mal stark davon aus, dass es sich hier um einen simplen Dreher handelt?
=> [Bug] Aufgabe Logging: Vertausche Methodenaufrufe (fix typo)

markdown/building/ci.md
In den aktuellen Webseiten nennt sich das CI bei Gitlab neuerdings 'GitLab CI/CD'
und bei GitHub entsprechend 'GitHub Actions'. Dieser Commit/PR korrigiert die
Begriffe im Dokument und verlinkt auch auf die korrigierten Demo-Videos.
=> VL Continuous Integration: Nutze korrekte Begriffe bei GitLab/GitHub

markdown/assignments/pool_concept/sheet02.md
Für Blatt02 wurde bereits Javadoc und Logging besprochen, d.h. das ist jetzt immer einzusetzen. Entsprechende(n) Hinweis/Erinnerung auf das Blatt?
Fixes #410
=> Fix #410: Ergänze Erinnerung zu Javadoc und Logging auf Blatt02

markdown/assignments/pool_dungeon/group_a/dungeon-start.md
Auf dem Dungeon-Startblatt eine Erinnerung an das Lerntagebuch unterbringen.
Fixes #408
=> Fix #408: Dungeon-Start: Ergänze Erinnerung an Lerntagebuch

data/schedule.yaml
JUnit Basics wurde in zwei Einheiten gesplittet: Testing Intro und JUnit Basics. 
Trage die neue Einheit im Schedule nach.
=> Schedule: ergänze Testing Intro

markdown/assignments/pool_concept/tasks/gradle.md, markdown/coding/codingrules.md
- B04: Der Link zum Repo (Gradle-Skript) wurde durch die Darstellung als Inline-Code optisch verdeckt. Jetzt ist der Link normaler Text und sollte dadurch wieder sichtbar sein.
- VL Coding-Rules: Setze die Vorlesung für die Zwischenzeit wieder auf "sketch", bis die Inhalte vorbereitet sind.
=> Fix Web: make link in B04 visible and hide empty Coding Rules lecture

markdown/org/grading.md
Der Hinweis zur Nachbearbeitung war unter "Workload" enthalten, konnte aber leicht übersehen werden. Ich habe den dort herausgenommen und unter einer eigenen Teilüberschrift wieder eingefügt, um die Sichtbarkeit zu erhöhen.
Zusätzlich habe ich den Hinweis verstärkt, dass die Punkte nur in der Woche angerechnet werden, wo die Nacharbeitung vorgestellt/abgegeben wird, d.h. die fallen dann mit den neuen Aufgaben unter die 15-Punkte-Regel.
Fixes #445
=> Orga: Verstärke Hinweis zu Punkte-Nachtrag für Nachbearbeitung

markdown/assignments/_index.md, markdown/org/grading.md
- füge die neuen 5P-Testaufgaben in den drei Dungeon-Gruppen in die Übersicht ein
- aktualisiere Gesamtpunkte Dungeon
- aktualisiere Gesamtpunkte Praktikum
- aktualisiere Puffer
Die drei neuen Testaufgaben im Dungeon erhöhen die Gesamtpunktzahl um 15 Punkte. Ich würde aber die Mindestpunkte für jeden Pool bei 50 Punkten lassen, und ich würde auch die 100% bei dem alten Wert belassen. Damit wird der Puffer entsprechend größer.
Fixes #442
=> Orga: passe (Gesamt-) Punkte an (neue Test-Aufgaben im Dungeon)

markdown/gui/layouts.md
Das Intro und das Outro wackelten ordentlich, für ein vernünftiges Freistellen vor dem Greenscreen war es scheinbar zu dunkel. Hier ein neuer Versuch mit neuem Intro und neuem Outro.
Fixes #481
=> [VL] Swing/Layout-Manager: Improve Intro/Outro

markdown/org/grading.md
=> [Org] Note&Credits: Klarstellung Themen und Notenspiegel E1/E2

markdown/java-jvm/regexp.md, markdown/modern-java/methodreferences.md
Die Quizzes für RegExp und Method References sind leider nicht rechtzeitig fertig geworden. Damit die Studis aber nicht länger auf das Material warten müssen, merge ich #487 und #488 vorerst ohne die Quizzes - diese werden über dieses Issue nachgereicht.
Fixes #496
=> [VL] Add quizzes to RegExp and Method References

markdown/coding/javadoc.md
Entferne Demo zu Javascript - möglicherweise ist das Zeigen einer Webseite zu Unterrichtszwecken rechtlich fragwürdig.
=> [VL] remove demo javascript

pm.bib
Füge den Eintrag `langid = {de}` bzw. `langid = {en}` zu jedem Bibtex-Eintrag hinzu. Dadurch wird bei der Konvertierung mit Pandoc von Bibtex nach YAML als Basis für Hugo die korrekte Schreibweise des Titels behalten. 
Man kann den Titel auch mit doppelten geschweiften Klammern schützen, aber sobald eine gemischte Schreibweise vorliegt, wird Pandoc im YAML ein `[...]{.nocase}` um den Titel wrappen, was Hugo nicht versteht.
fixes #58
=> [BUG] Fix Groß-/Kleinschreibung in Bib-File

markdown/_index.md, markdown/assignments/_index.md, markdown/assignments/pool_concept/_index.md, markdown/assignments/pool_dungeon/_index.md, markdown/assignments/pool_dungeon/group_a/_index.md, markdown/assignments/pool_dungeon/group_b/_index.md, markdown/assignments/pool_dungeon/group_c/_index.md, markdown/building/_index.md, markdown/coding/_index.md, markdown/database/_index.md, markdown/frameworks/_index.md, markdown/generics/_index.md, markdown/git/_index.md, markdown/gui/_index.md, markdown/java-jvm/_index.md, markdown/modern-java/_index.md, markdown/org/_index.md, markdown/pattern/_index.md, markdown/testing/_index.md, markdown/threads/_index.md
Im Hugo-Re-Learn-Theme 5.x sind die Chapter so organisiert, dass der Titel als H1-Header genutzt wird. 
- Baue alle `_index.md` so um, dass keine H1-Header mehr existieren
- Nutze bei Bedarf neben `title` auch `menuTitle`
- Ziehe `hidden: true` auf die letzte Zeile (davor eine Leerzeile), um es besser sichtbar zu machen
=> [VL] Fix landing pages

config.yaml
Im neuen ILIAS 7.x funktionieren bei den HTML-Lernmodulen die "pretty URLs" nicht mehr und es musste auf "ugly URLs" umgestellt werden.
Allerdings funktioniert das an drei Stellen scheinbar nicht:
1. Logo => hänge ein "/index.html" an die Base-URL an
2. Menu Shortcuts => Fake-URLs statt der normalen Hugo-URLs
3. Breadcrumbs => deaktiviert
Mal sehen, wie lange der Workaround in (2) funktionieren wird ...
=> Fix ILIAS 7.x Lern-Modules

CREDITS.md
Das Repo [Hugo-Lecture](https://github.com/cagix/Hugo-Lecture) ist nun Teil von [pandoc-lecture](https://github.com/cagix/pandoc-lecture/tree/master/hugo/hugo-lecture) - Aktualisiere den Eintrag in den Credits.
fixes #623
=> Credits: replace Hugo-Lecture w/ pandoc-lecture

markdown/assignments/group_loot/freie_aufgabe.md, markdown/assignments/group_loot/lockpicking.md, markdown/assignments/group_loot/schatzkiste.md, markdown/assignments/group_loot/testen.md
fixes #651 
Führt zwei neue Aufgaben ein.
1. Erweitern der vorhanden Schatzkiste, um sie zu einer Monter-Schatzkiste zu machen
2. Implementieren eines Lockpicking-Minigames
- anpassen der weights 
- Baut auf #642
=> [Aufgaben ] add neue Aufgaben group_item/schatzkiste und group_item/lockpicking

markdown/org/resources.md
- add link to Java Developer RoadMap: https://medium.com/javarevisited/the-java-programmer-roadmap-f9db163ef2c2
- link to https://dev.java/learn/ was added earlier ...
fixes #563
=> [Org] add link to Java Programmer Roadmap

data/schedule.yaml
Gastvortrag zu JUnit/Mocking in der Praxis von Daniel in KW19, also konkret Freitag, 12.05., 16:30 - 18:00 Uhr
fixes #656
=> [Schedule] Gastvortrag zu JUnit/Mocking in der Praxis

markdown/org/faq.md
Das Beispiel zur Konzeptskizze ist nicht ECS-konform. Dazu wird in der FAQ ein expliziter Hinweis eingebaut.
fixes #653
=> [FAQ] Hinweis auf nicht ECS-konformes Beispiel der Konzeptskizze

markdown/org/faq.md
Jede Aufgabe kann nur 1x gemacht werden. Freie Aufgaben (mit unterschiedlichen Inhalten) können mehrfach bearbeitet werden.
fixes #654
=> [FAQ] Freie Aufgaben können mehrfach gewählt werden

data/schedule.yaml, markdown/_index.md, markdown/org/faq.md, markdown/org/grading.md
- Schedule: passe die Abgabezeiten an (neue Abgabe: Donnerstag, 8 Uhr)
- Schedule: ergänze Deadline für Feedback (Freitag, 8 Uhr)
- Landing Page: formuliere Abgabehinweis unter Schedule-Tabelle generisch
- Grading: reduziere Text (nur prüfungsrelevante Inhalte)
- Grading: entferne konkrete Zeiten
- Grading: formuliere generischer
- FAQ: entferne Redundanzen
- FAQ: entferne konkrete Zeiten
löst zum Teil #682
=> [ORG] Clean-up: Schedule, Grading, FAQ

markdown/_index.md, markdown/assignments/_index.md, markdown/assignments/b01a.md, markdown/assignments/b01b.md, markdown/assignments/b02a.md, markdown/assignments/b02b.md, markdown/assignments/b03a.md, markdown/assignments/b03b.md, markdown/assignments/b04a.md, markdown/assignments/b04b.md, markdown/assignments/b05a.md, markdown/assignments/b05b.md, markdown/assignments/b06.md, markdown/org/faq.md, markdown/org/grading.md
Ab Zyklus 2 (also Zyklen 2..5 plus Sonderabgabe) sollen die Implementierungen nicht mehr als Zip-File im ILIAS hochgeladen werden. Stattdessen sollen sich die Studis auf einem System ihrer Wahl (GitHub, GitLab, Bitbucket, Git03(!)) ein öffentliches Repo einrichten und die zur Abgabe vorgesehenen Dateien in einem Pull-/Merge-Request zusammensammeln. Den Link zu diesem PR/MR sollen sie im ILIAS abgeben.
Anpassen:
fixes #694
=> [Org] Ergänze Abgabe-Artefakte: PDF, ZIP, Link

markdown/org/faq.md
Zusätzlich zur Abgabe in der letzten Woche kann man einmal im Semester bei der Vorstellung im Praktikum fehlen, wenn man sich vorher mit dem Dozenten abgestimmt hat und auch aktiv an der Teamleistung teilgenommen hat.
=> [FAQ] Ergänze Ausnahme für Krankheit/familiäre Notfälle

markdown/java-jvm/collections.md
In der Sitzung zu Collections sind drei Gifs eingebettet. Interessanterweise kann entweder Hugo oder der verwendete Style (Relearn-Theme) damit nichts anfangen und stellt die Abbildungen nur als leere Kästen dar. 
Dieser PR ersetzt die Abbildungen mit .gif in der Collections-Sitzung durch Links auf die Animation im Repo auf Github.
=> [VL] fix issue w/ gif in collection session

.editorconfig
- Nutze für Windows-Dateien statt `lf` ein `crlf` als Zeilenende
- In YAML-Dateien rücke nur 2 Spaces ein (statt 4)
=> [Tool] Ergänze .editorconfig für Windows- und YAML-Dateien

markdown/assignments/_index.md, markdown/assignments/group_basics/_index.md, markdown/assignments/group_loot/_index.md, markdown/assignments/group_monster/_index.md, markdown/building/_index.md, markdown/coding/_index.md, markdown/database/_index.md, markdown/frameworks/_index.md, markdown/generics/_index.md, markdown/git/_index.md, markdown/gui/_index.md, markdown/java-jvm/_index.md, markdown/modern-java/_index.md, markdown/org/_index.md, markdown/pattern/_index.md, markdown/testing/_index.md, markdown/threads/_index.md
Das `chapter`-Template ist irgendwie kaputt: Die Fußzeile wird viel zu groß dargestellt. Das betrifft auch das originale `chapter`-Template ... Wir wechseln hier auf das `default`-Template, wodurch die Fußzeile wieder passt. Einzig der `<hr>` unter dem Titel fehlt ...
=> Tool: switch to 'default' layout for chapter landing pages

homework/b01.md, homework/b02.md, homework/b03.md, homework/b04.md, homework/b05.md, homework/b06.md, homework/b07.md, homework/b08.md, homework/b09.md
this is quite a duplication of information (from readme and discussions) and i would normally like to avoid that. but this change should help students to keep track.
closes #1021
=> homework: add instructions for completion and submission
