Programmiermethoden-CampusMinden/Prog2-Lecture

- README.md
> Update License Statement

- Makefile
> new and improved Makefile

- markdown/_index.md
- markdown/assignments/_index.md
- markdown/assignments/sheet01/index.md
- markdown/misc/_index.md
- markdown/misc/schedule/index.md
Escape all Hugo shortcodes with `''{=markdown}`
> escape markdown

- Makefile
from https://github.com/KI-Vorlesung/Lecture/pull/122
> add improvements to makefile

- markdown/assignments/sheet01.md
removing partial challenges
This partial was not used at all, thus removing it now. Update also archetypes accordingly.
fixes #151
> Challenges: Remove partial

- markdown/assignments/sheet01.md
- markdown/assignments/sheet02/index.md
Layouts Assignments: allow for single markdown file or page bundle
Partials Assignments: fix header
Archetypes Assignment: fix YAML
Example Sheets: fix single markdown file example and add page-bundle example
Fixes #153
> Assignments: adapt layouts and partials

- config.yaml
Privacy: update hugo config according to https://gohugo.io/about/hugo-and-gdpr/
> Privacy: update hugo config

- .github/actions/alpine-pandoc-hugo/install-packages.sh
> hugo: update to latest version (0.92.2)

- config.yaml
> Hugo Config: Update Base-URL (PM, S22)

- config.yaml
> fix #179: switch back to light mode as default

- markdown/database/_index.md
- markdown/database/jdbc.md
- markdown/frameworks/_index.md
- markdown/frameworks/guava.md
> Strukturen anpassen: -Spring, +JDBC, +Frameworks

- .github/workflows/hugo.yaml
- .github/workflows/slides.yaml
> workflow slides: build only on master and manually triggered

- .github/workflows/hugo.yaml
- .github/workflows/slides.yaml
> Worklows: Update actions/checkout to v3

- markdown/assignments/pool_a/start/index.md
fixes #67
- anpassen der Punkte von 5 auf 10
> rewrote start

- markdown/assignments/pool_k/tasks/_index.md
> add folder and landing page for tasks

- markdown/git/branches.md
> Vorlesung: Git Branches

- markdown/git/bisect.md
> Vorlesung: Git Bisect

- markdown/coding/javadoc.md
> Vorlesung: Javadoc

- markdown/generics/classes-methods.md
- markdown/generics/src/classes/GenericClasses.java
- markdown/generics/src/methods/GenericMethods.java
> Vorlesung: Generics: Klassen und Methoden

- markdown/generics/bounds-wildcards.md
- markdown/generics/src/bounds/Cps.java
- markdown/generics/src/wildcards/v1/X.java
- markdown/generics/src/wildcards/v2/X.java
- markdown/generics/src/wildcards/v3/X.java
> Vorlesung: Generics: Bounds und Wildcards

- markdown/generics/type-erasure.md
> Vorlesung: Generics: Type Erasure

- markdown/assignments/pool_k/tasks/git_branches.md
Fixes #102 
Ist 1zu1 die alte Aufgabe aus dem Tutorium.
> Add: Konzeptaufgabe Git Branches

- markdown/assignments/pool_k/sheet01/index.md
> Aufgaben: Überarbeite Sheet 01

- markdown/assignments/pool_k/sheet01/index.md
- markdown/org/resources.md
- pm.bib
siehe Diskussion in https://github.com/PM-Dungeon/studi-template/issues/1
> Orga: Ressourcen

- markdown/assignments/_index.md
- markdown/assignments/pool_a/_index.md
- markdown/assignments/pool_b/_index.md
- markdown/assignments/pool_c/_index.md
- markdown/assignments/pool_k/_index.md
Überarbeite die Landing-Pages der Praktikumsseiten, damit sie (a) self-contained sind und (b) mit den Informationen auf "Note & Credits" (siehe #317) übereinstimmen.
TODO:
> Aufgaben: Überarbeite Landing-Pages

- markdown/assignments/pool_k/tasks/logging.md
> Add: Konzeptaufgabe Logging

- junit_basics/SpecialArrayList.java
- markdown/assignments/pool_k/tasks/junit_basics.md
> Add: Konzeptaufgabe JUnit Basics

- markdown/assignments/pool_a/skills/index.md
> Aufgabe: Pool A: Skills

- markdown/assignments/pool_a/fallen/index.md
> Aufgabe: Pool A: Fallen

- markdown/assignments/pool_a/crafting/index.md
> Aufgabe: Pool A: Crafting

- markdown/assignments/pool_a/charakterklassen/index.md
Fixes #69
- Voraussetzung angegeben
> Aufgabe: Pool A: Charakterklassen

- markdown/assignments/pool_b/monster/index.md
> Aufgabe: Pool B: Monster

- markdown/assignments/pool_b/nahkampf/index.md
> Aufgabe: Pool B: Nahkampf

- markdown/assignments/pool_b/magie/index.md
> Aufgabe: Pool B: Magie

- markdown/assignments/pool_b/xp/index.md
> Aufgabe: Pool B: XP

- markdown/assignments/pool_b/schlaue_monster/index.md
> Aufgabe: Pool B: Schlaue Monster

- markdown/assignments/pool_b/boss_monster/index.md
> Aufgabe: Pool B: Boss Monster

- markdown/assignments/pool_c/item/index.md
> Aufgabe: Pool C: Item

- markdown/assignments/pool_a/start/index.md
- markdown/assignments/pool_c/taschen/index.md
> Aufgabe: Pool C: Taschen

- markdown/assignments/pool_c/hud/index.md
> Aufgabe: Pool C: HUD

- markdown/assignments/pool_c/inventar_ui/index.md
> Aufgabe: Pool C: Inventar UI 

- markdown/assignments/pool_a/start/index.md
- markdown/assignments/pool_c/npc/index.md
> Aufgabe: Pool C: NPC

- markdown/assignments/pool_c/dialogsystem/index.md
> Aufgabe: Pool C: Dialogsystem

- markdown/assignments/pool_c/quests/index.md
> Aufgabe: Pool C: Quests

- markdown/assignments/pool_c/shop/index.md
> Aufgabe: Pool C: Shop

- markdown/assignments/pool_a/charakterklassen.md
- markdown/assignments/pool_a/skills.md
- markdown/assignments/pool_a/speichern_und_laden.md
- markdown/assignments/pool_b/boss_monster.md
- markdown/assignments/pool_b/fernkampf.md
- markdown/assignments/pool_b/gameover.md
- markdown/assignments/pool_b/magie.md
- markdown/assignments/pool_b/monster.md
- markdown/assignments/pool_b/nahkampf.md
- markdown/assignments/pool_b/xp.md
- markdown/assignments/pool_c/hud.md
- markdown/assignments/pool_c/item.md
- markdown/assignments/pool_c/schatzkiste.md
- markdown/org/resources.md
> Aufgaben: fix weird whitespace problem

- markdown/assignments/pool_k/tasks/mocking.md
> Add: Konzeptaufgabe Mocking

- markdown/assignments/pool_k/sheet02.md
- markdown/assignments/pool_k/tasks/factory_method.md
- markdown/assignments/pool_k/tasks/logging.md
> Aufgaben: Überarbeite Sheet 02

- markdown/generics/generics-polymorphism.md
- markdown/generics/src/arrays/X.java
> Vorlesung: Generics: Polymorphie

- markdown/org/grading.md
Fixes #371  
see meeting on 01.04.22
> Orga: Update Grading (formale Abzüge)

- markdown/assignments/_index.md
> Landing-Page Praktikum: Pools durchnummerieren

- README.md
- markdown/_index.md
> Förderung: Hinweis auf Förderung durch DH.NRW einbauen

- markdown/coding/logging.md
- markdown/generics/bounds-wildcards.md
- markdown/generics/classes-methods.md
- markdown/generics/generics-polymorphism.md
- markdown/pattern/factory-method.md
- markdown/pattern/src/strategy/SortDefault.java
- markdown/pattern/src/strategy/SortOwnCrit.java
- markdown/pattern/src/strategy/Studi.java
- markdown/pattern/src/strategy/TranslatorExample.java
- markdown/pattern/strategy.md
> Vorlesung: add links to code snippets

- .github/actions/alpine-pandoc-hugo/install-packages.sh
see https://github.com/Compilerbau/Lecture/issues/89
> fix warning regarding missing gincltex package

- markdown/assignments/pool_concept/tasks/junit_advanced_bank.md
Add: Konzeptaufgabe JUnit Advanced Bank
F #111 (0,5)
> Add: Konzeptaufgabe JUnit Advanced Bank

- markdown/assignments/pool_concept/tasks/junit_advanced_rsv.md
Add: Konzeptaufgabe JUnit Advanced RSV
Vorgabe im .md
Fixes #111
> Add: Konzeptaufgabe JUnit Advanced RSV

- markdown/assignments/pool_concept/tasks/generics_1.md
Einmal das Bereitstellen der Generics 1 Konzeptaufgabe.
#114
> add konzeptaufgabe generics 1

- markdown/building/gradle.md
> Vorlesung: Build: Gradle

- markdown/assignments/pool_dungeon/group_a/dungeon-start.md
see https://github.com/PM-Dungeon/dungeon-starter/issues/88
> rename desktop to dungeon-starter

- markdown/assignments/pool_concept/tasks/swing.md
Fixes #122
ggf. könnte man die Spiellogik vorgeben.
> Add Konzeptaufgabe: Swing

- markdown/assignments/pool_concept/tasks/strategy_pattern.md
Fixes https://github.com/PM-Dungeon/PM-Lecture/issues/107
> Add: Konzeptaufgabe: Strategy Pattern

- markdown/assignments/pool_concept/tasks/generics_2.md
> Add: Konzeptaufgabe: Generics_2

- markdown/assignments/pool_concept/sheet01.md
> Fix 409: Ergänze Hinweise auf Blatt01

- markdown/assignments/pool_dungeon/group_a/dungeon-start.md
Ergänze Punkteverteilung für die Tutoren: 3+3+4P
Fixes #407
> Fix #407: Dungeon-Starter: ergänze Punkteverteilung

- data/schedule.yaml
- markdown/coding/codingrules.md
- markdown/coding/smells.md
> Vorlesung: Coding: Smells

- markdown/assignments/pool_concept/tasks/gradle.md
Fixes #123
Eigentlich würde ich gern die Erstellung der Lösung in https://github.com/PM-Dungeon/Homework-Solutions/pull/13 abwarten, aber das dauert einfach zu lange. Die Studis brauchen die Aufgabe für nächste Woche.
> Add: Konzeptaufgabe: Gradle

- markdown/assignments/pool_concept/sheet04.md
- markdown/assignments/pool_concept/tasks/junit_advanced_rsv.md
- markdown/assignments/pool_concept/tasks/junit_basics.md
- #110 
- #111 
- #123 (nur gradle)
Fixes #94
> Aufgaben: Überarbeite Sheet 04

- markdown/assignments/pool_concept/sheet05.md
- markdown/assignments/pool_concept/tasks/mocking.md
Fixes #95
- Hinweise auf Coding-Style (war in W6/KW16 drin und ist hier sogar explizit Thema)
- Mocking mit Mockito
- Identifizieren von Smells und Anwendung von Refactoring
Edit: Fragen fürs Review:
> Aufgaben: Überarbeite Sheet 05

- markdown/assignments/pool_dungeon/group_a/crafting.md
Fixes #423 
Setze Punkte von jetzt 3 auf die ursprünglich gewollten 5 Punkte hoch.
> Fix #423: Dungeon Task A:Crafting should be worth 5 pts

- markdown/assignments/pool_concept/tasks/observer_pattern.md
Einmal das Hinzufügen der Konzeptaufgabe für das Observer Pattern.
https://github.com/PM-Dungeon/PM-Lecture/issues/106
> Add: Konzeptaufgabe Observer Pattern

- markdown/testing/mockito.md
- markdown/testing/src/Mockito/main/java/mock/IWuppiWarenlager.java
- markdown/testing/src/Mockito/main/java/mock/WuppiStore.java
- markdown/testing/src/Mockito/main/java/spy/IWuppiWarenlager.java
- markdown/testing/src/Mockito/main/java/spy/Wuppi.java
- markdown/testing/src/Mockito/main/java/spy/WuppiStore.java
- markdown/testing/src/Mockito/main/java/spy/WuppiWarenlager.java
- markdown/testing/src/Mockito/main/java/stub/IWuppiWarenlager.java
- markdown/testing/src/Mockito/main/java/stub/IWuppiWarenlagerStub.java
- markdown/testing/src/Mockito/main/java/stub/WuppiStore.java
- markdown/testing/src/Mockito/main/java/stub/WuppiWarenlagerStub.java
- markdown/testing/src/Mockito/main/java/verify/FluppisListe.java
- markdown/testing/src/Mockito/test/java/mock/WuppiWarenlagerMockTest.java
- markdown/testing/src/Mockito/test/java/spy/WuppiWarenlagerSpyTest.java
- markdown/testing/src/Mockito/test/java/stub/WuppiWarenlagerStubTest.java
- markdown/testing/src/Mockito/test/java/verify/VerifyFluppisListeTest.java
Fixes https://github.com/PM-Dungeon/PM-Lecture/issues/220
> VL neu: Testing: Mocking

- markdown/assignments/pool_concept/tasks/flyweight_pattern.md
Die Aufgabe für das Flyweight Pattern.
fixes #262
> Add: Konzeptaufgabe Flyweight Pattern

- markdown/org/grading.md
- markdown/org/lerntagebuch.md
Zentrale Frage: Welche Techniken kenne ich und kann ich sinnvoll für die Lösung der Aufgabe verwenden (und warum)?
Passe Orga (Note&Credits) und die Vorlage für das Lerntagebuch an.
Fixes #441
> Orga: Verstärke Hinweis im Lerntagebuch

- markdown/org/grading.md
> Orga: Keine Abzüge bei Tests (außer es wird in der Aufgabe gefordert)

- markdown/assignments/pool_dungeon/group_a/testen.md
- markdown/assignments/pool_dungeon/group_b/testen.md
- markdown/assignments/pool_dungeon/group_c/testen.md
> New Dungeon-Tasks: Fix Typos

- markdown/assignments/_index.md
- markdown/org/grading.md
> [Orga] Helfen im Framework

- markdown/assignments/pool_concept/tasks/type-object.md
Fixes #263
siehe https://github.com/PM-Dungeon/Homework-Solutions/pull/27 / https://github.com/PM-Dungeon/Homework-Solutions/issues/26
> Add task for type-object pattern

- markdown/pattern/type-object.md
> Vorlesung: Pattern: Type Object

- markdown/java-jvm/enums.md
- markdown/java-jvm/src/enums/FinalDemo.java
- markdown/java-jvm/src/enums/v1/Studi.java
- markdown/java-jvm/src/enums/v2/Studi.java
- markdown/java-jvm/src/enums/v3/Fach.java
- markdown/java-jvm/src/enums/v3/Studi.java
> Vorlesung: Java/JVM: Enumerationen

- markdown/assignments/pool_concept/sheet06.md
- #263 / https://github.com/PM-Dungeon/Homework-Solutions/issues/26
- #106 
- ~~#333~~
- ~~#262~~
- ~~#120~~
---
Fixes #96
> Aufgaben: Überarbeite Sheet 06

- markdown/assignments/pool_concept/tasks/mocking.md
Siehe auch https://github.com/PM-Dungeon/Homework-Solutions/issues/31
> Update: Konzeptaufgabe Mocking

- data/schedule.yaml
- markdown/pattern/singleton.md
- markdown/pattern/src/singleton/SingletonEager.java
- markdown/pattern/src/singleton/SingletonLazy.java
> Vorlesung: Pattern: Singleton

- markdown/java-jvm/reflection.md
- markdown/java-jvm/src/reflection/ClassLoaderDemo.java
- markdown/java-jvm/src/reflection/ReflectionDemo.java
- markdown/java-jvm/src/reflection/Studi.java
- markdown/java-jvm/src/reflection/Wuppie.java
> Vorlesung: Java/JVM: Reflection

- markdown/assignments/pool_concept/tasks/template_method_pattern.md
> Konzeptaufgabe: Template Method Pattern

- markdown/assignments/pool_concept/tasks/annotations.md
Fixes https://github.com/PM-Dungeon/PM-Lecture/issues/121
> Add: Konzeptaufgabe Annotations

- markdown/assignments/pool_concept/tasks/defaultmethoden.md
fixes #116
Der sehr kurze Aufgabentext für Defaultmethoden.
> Add: Konzeptaufgabe Defaultmethoden

- markdown/assignments/pool_concept/tasks/relection.md
> Add Konzeptaufgabe Reflection

- markdown/java-jvm/serialisation.md
- markdown/java-jvm/src/serial/SerializableStudi.java
- markdown/java-jvm/src/serial/TestSerializableStudi.java
> Vorlesung: Java/JVM: Serialisierung

- markdown/java-jvm/serialisation.md
add missing "markdown/" in path ... :/
> Lecture Serialisation: fix link to demo code

- markdown/frameworks/intro.md
Selbstlerntest ist nachträglich fertig geworden und wird mit diesem PR eingebaut.
Fixes #485
> [VL] Frameworks: add Quiz

- markdown/assignments/pool_concept/tasks/lambda.md
Fixes https://github.com/PM-Dungeon/PM-Lecture/issues/117
> Add: Konzeptaufgabe: Funktionsinterfaces, Lambdas und Methodenreferenzen

- markdown/assignments/pool_concept/sheet08.md
> Konzeptaufgabe: Sheet08

- markdown/java-jvm/regexp.md
- markdown/java-jvm/src/regexp/Backref.java
- markdown/java-jvm/src/regexp/Groups.java
- markdown/java-jvm/src/regexp/MatchFind.java
- markdown/java-jvm/src/regexp/Quantifier.java
- markdown/java-jvm/src/regexp/StringSplit.java
> Vorlesung: Java/JVM: RegExp

- markdown/assignments/pool_concept/tasks/visitor_pattern.md
Fixes https://github.com/PM-Dungeon/PM-Lecture/issues/105
> Add Konzeptaufgabe: Visitor Pattern

- markdown/assignments/pool_concept/sheet09.md
Fixes #99
- #118 [Tutorium]
- #105 [Blatt 09]
- #264 [Tutorium]
- #265 [Tutorium]
> Aufgaben: Überarbeite Sheet 09

- markdown/assignments/pool_concept/tasks/stream_api.md
Die Aufgabe für Stream API,
https://github.com/PM-Dungeon/PM-Lecture/issues/118
> Add: Konzeptaufgabe Stream API

- markdown/modern-java/records.md
- markdown/modern-java/src/records/DemoRecords.java
- markdown/modern-java/src/records/Studi.java
- markdown/modern-java/src/records/StudiR.java
- markdown/modern-java/src/records/StudiS.java
- markdown/modern-java/src/records/StudiT.java
> Vorlesung: Modern Java: Records

- data/schedule.yaml
- markdown/modern-java/optional.md
- markdown/modern-java/src/optional/streams/Demo.java
- markdown/modern-java/src/optional/streams/LSF.java
- markdown/modern-java/src/optional/streams/Studi.java
- markdown/modern-java/src/optional/teaser/Demo.java
- markdown/modern-java/src/optional/teaser/LSF.java
- markdown/modern-java/src/optional/teaser/Studi.java
- markdown/modern-java/src/optional/traditional/Demo.java
- markdown/modern-java/src/optional/traditional/LSF.java
- markdown/modern-java/src/optional/traditional/Studi.java
> [VL] Modern Java: Optional

- markdown/modern-java/stream-api.md
> [VL] Quiz für Streams nachreichen

- markdown/modern-java/records.md
> [VL] Quiz für Record-Klassen nachreichen

- markdown/modern-java/records.md
> [VL] Hinweis: Record-Klassen sind final 

- markdown/modern-java/optional.md
> [VL] Quiz für Optional nachreichen

- markdown/assignments/pool_concept/tasks/optional.md
> Add: Konzeptaufgabe Optional

- markdown/assignments/pool_concept/tasks/command_pattern.md
fixes https://github.com/PM-Dungeon/PM-Lecture/issues/265
> Add: Konzeptaufgabe Command Pattern

- markdown/threads/src/synchronised/Deadlock.java
- markdown/threads/src/synchronised/MethodSync.java
- markdown/threads/src/synchronised/ObjSync.java
- markdown/threads/src/synchronised/Staffel.java
- markdown/threads/src/synchronised/Teaser.java
- markdown/threads/synchronisation.md
> [VL] Threads: Synchronisierung

- markdown/threads/highlevel.md
- markdown/threads/src/executor/ExecutorDemo.java
- markdown/threads/src/forkjoin/ForkJoin.java
- markdown/threads/src/lock/LockObjects.java
- markdown/threads/src/lock/TradMonitors.java
- markdown/threads/src/lock/TraditionalSynchronized.java
- markdown/threads/src/misc/SwingWorkerDemo.java
> [VL] Threads: High-Level Konzepte

- markdown/assignments/pool_concept/tasks/exceptions.md
> Add: Konzeptaufgae Exceptions 

- markdown/java-jvm/exceptions.md
> [VL] Quiz für Exceptions nachreichen

- markdown/assignments/pool_concept/tasks/multithreading.md
> Add: Aufgabe: Multithreading

- markdown/assignments/pool_concept/sheet10.md
`Kunde`: 0.5P Runnable, 1P run(), 2P Synchronisation und Warten auf Rechnungen
`Transaktion`: 0.5P Runnable, 1P run(), 2P Synchronisation mit `Konto`
`Bank`: 2P Starten der Threads über Executor-API
`Geldeintreiber`: 1P run()
Abzüge: 0.5P für zu viel oder zu wenig Synchronisation
> Aufgaben: Überarbeite Sheet 10

- markdown/building/ant.md
- markdown/building/src/Dockerfile
- markdown/building/src/Makefile
- markdown/building/src/ant/Hello.java
- markdown/building/src/ant/build.xml
- markdown/building/src/ant/hello.xml
- markdown/building/src/ant/ivy.xml
- markdown/building/src/ant/ivydemo.xml
> [VL] Build: Ant

- markdown/building/maven.md
> [VL] Quiz für Build: Maven nachreichen

- markdown/building/maven.md
- fix url to video (proper escaping)
- fix tldr (use full sentences)
> [VL] Maven: fix url and tldr

- markdown/java-jvm/configuration.md
> [VL] Configuration: fix readings

- markdown/threads/highlevel.md
> [VL] Quiz für Threads: High-Level Konzepte nachreichen

- markdown/java-jvm/configuration.md
> [VL] Quiz für Java/JVM: Configuration nachreichen

- markdown/building/docker.md
> [VL] Quiz für Build: Docker nachreichen

- config.yaml
- markdown/org/exam.md
- markdown/org/grading.md
> [VL]: Exams

- markdown/coding/refactoring.md
- markdown/coding/smells.md
- markdown/git/basics.md
> [ORG] Zitate und Fremdmaterial prüfen: TULLU-Regel

- markdown/pattern/visitor.md
> [VL] Alle Links zu Code-Beispielen nochmal prüfen 

- config.yaml
- markdown/_index.md
- markdown/building/ant.md
- markdown/building/gradle.md
- markdown/coding/javadoc.md
- markdown/coding/logging.md
- markdown/coding/smells.md
- markdown/generics/generics-polymorphism.md
- markdown/generics/type-erasure.md
- markdown/git/branches.md
- markdown/git/remotes.md
- markdown/gui/java2d.md
- markdown/java-jvm/annotations.md
- markdown/java-jvm/configuration.md
- markdown/modern-java/src/methodreferences/CollectionStreams.java
- markdown/modern-java/src/methodreferences/ThreadStarter.java
- markdown/org/exam.md
- markdown/org/syllabus.md
- markdown/testing/testing-intro.md
> [ORG] Offenen Kursraum (ILIAS) einrichten

- .github/actions/alpine-pandoc-hugo/Dockerfile
- .github/actions/alpine-pandoc-hugo/install-packages.sh
> [TOOLING] Update Docker

- README.md
- markdown/_index.md
> [ORG] add url to 'Digi Fellowships' project

- .github/workflows/.mlc_config.json
- .github/workflows/mlc.yaml
- .github/workflows/mlc_config.json
- fix path to configuration
- add more exclude pattern
- fix issue with GitHub links (https://github.com/gaurav-nelson/github-action-markdown-link-check#github-links-failure-fix)
> [Action] Fix MLC action

- markdown/assignments/group_loot/npc.md
fixes #649 
- Codeanlyse: Welche Komponents braucht ein NPC?
- NPC Geist der den Spieler verfolgt und manchmal wandern geht
- Grabstein, wenn dieser gefunden wurde soll der Geist was machen (Spieler belohnen/bestrafen)
- 
baut auf #642
> [Aufgabe] rework Aufgabe group_loot/npc

- markdown/assignments/group_loot/item.md
fixes #650 
Passt die Aufgabe an die neuen Umstände an
- Codeanalyse des vorhandenen Konzeptes
- Eigene Items mit Funktionen bauen
- Taschen bauen
baut auf #642 auf
> [Aufgabe] rework Aufgabe group_loot/item

- markdown/assignments/_index.md
- markdown/frameworks/dungeon.md
- markdown/org/faq.md
- markdown/org/resources.md
> [VL] Ergänze Hinweise auf nette ShPD-Einführungsvideos

- markdown/org/faq.md
1. Bounty-Aufgaben = Issues, die in der Suchabfrage erscheinen
2. Punkte: 5P vs. 10P (zus. Label)
3. Bounty-Aufgaben kann jeder frei bearbeiten - Punkte wie am Label
4. Bounty-Aufgaben können **zusätzlich** per Pull-Request eingereicht werden:
- Bei Akzeptanz (Merge) bis zu 5 Punkte zusätzlich
- Es wird üblicherweise genau ein PR gemergt - Entscheidung liegt beim Team/Dozenten, kein Anspruch auch Merge
- Nach dem Merge gibt es die Bounty-Aufgabe nicht mehr
5. Zusätzlich können Issues aus dem Issue-Tracker gefixt werden. Absprache im Issue notwendig! Wie bei Bounty: Punkte für die Umsetzung plus Punkte für Merge.
fixes #655
> [FAQ] formuliere Bounty-Aufgaben klarer

- markdown/org/faq.md
- markdown/org/grading.md
Halte Grading so schlank wie möglich und so präzise wie nötig, zusätzliche Erklärungen dann in die FAQ.
> [FAQ] Gleiche FAQ und Grading ab

- data/schedule.yaml
- markdown/org/faq.md
- FAQ: fix link
- Schedule: passe Abgabezeit Sonderabgabe an andere Abgaben an
> [Org] Fix typos

- markdown/modern-java/lambdas.md
> [VL] Add code review example (Vertiefung Lambda)

- markdown/git/basics.md
- markdown/git/branches.md
- markdown/git/remotes.md
> [VL] Add some interactive Git tutorials as challenges

- markdown/org/faq.md
Bei "eigenem Team" trage in die Textfelder einen "*" ein und beachte die Ja/Nein- und Sterne-Fragen nicht. Trage zusätzlich im Feld "eigenes Team" ein "ja" ein.
fixes #695
> [FAQ] Ergänze Hinweis zu Peer-Feedback bei eigenem Team

- data/schedule.yaml
Füge zu den Abgabedaten im Schedule noch je ein "Praktikum: Fr, 04.04." hinzu. Dann sind die Daten im Schedule und auf den Übungsblättern in sich vollständig.
> [Org] Add 'Praktikum' to schedule

- data/schedule.yaml
- markdown/assignments/b01b.md
- markdown/assignments/b02b.md
- markdown/assignments/b03b.md
- markdown/assignments/b04b.md
- markdown/assignments/b05b.md
- markdown/assignments/b06.md
see https://github.com/cagix/pandoc-lecture/pull/51
> [Org] Adjust schedule / yaml headers to changes in cagix/pandoc-lecture/pull/51

- markdown/assignments/group_basics/charakterklassen.md
- markdown/assignments/group_basics/fallen.md
- markdown/assignments/group_basics/freie_aufgabe.md
- markdown/assignments/group_basics/skills.md
- markdown/assignments/group_basics/speichern_und_laden.md
- markdown/assignments/group_basics/testen.md
- markdown/assignments/group_loot/dialogsystem.md
- markdown/assignments/group_loot/freie_aufgabe.md
- markdown/assignments/group_loot/item.md
- markdown/assignments/group_loot/lockpicking.md
- markdown/assignments/group_loot/npc.md
- markdown/assignments/group_loot/quests.md
- markdown/assignments/group_loot/schatzkiste.md
- markdown/assignments/group_loot/shop.md
- markdown/assignments/group_loot/testen.md
- markdown/assignments/group_monster/boss_monster.md
- markdown/assignments/group_monster/fernkampf.md
- markdown/assignments/group_monster/freie_aufgabe.md
- markdown/assignments/group_monster/gameover.md
- markdown/assignments/group_monster/monster.md
- markdown/assignments/group_monster/nahkampf.md
- markdown/assignments/group_monster/testen.md
gehört noch zu #705 ... (vergessen, dass die Tasks auch "Assignments" sind und Punkte notiert haben)
> [Org] Adjust assignment yaml headers to changes in cagix/pandoc-lecture/pull/51

- markdown/_index.md
- markdown/org/syllabus.md
- [Org] Fix typo in landing page
- [Org] Improve wording in syllabus (topics)
> [Org] Improve Landing Page and Syllabus (rewording)

- markdown/org/faq.md
Füge Hinweis für die SSH-Key-Generierung und Konfiguration zur FAQ hinzu
> [FAQ] Add generating SSH keys for GitHub

- markdown/modern-java/lambdas.md
- markdown/modern-java/src/functionalinterfaces/DemoFI.java
- markdown/modern-java/stream-api.md
> [VL] Ergänze Video zu Functional Interfaces aus dem JDK

- markdown/assignments/_index.md
- markdown/org/faq.md
see https://github.com/Programmiermethoden/Dungeon/issues/586
> [ORG] Cleanup label: update links to bounty tasks

- markdown/building/maven.md
- markdown/coding/smells.md
- markdown/git/basics.md
- markdown/git/intro.md
- markdown/git/workflows.md
- markdown/gui/java2d.md
- markdown/java-jvm/enums.md
- markdown/org/syllabus.md
- markdown/testing/testing-intro.md
Fortsetzung von https://github.com/Programmiermethoden/PM-Lecture/pull/741 - da waren doch noch einige Buttons, die dem ORCA-Team durchgerutscht sind.
> [ORCA] fix remaining buttons

- homework/b05.md
- readme.md
> Homework: add B05

- homework/b02.md
> Homework: finalise B02

- homework/b03.md
> Homework: finalise B03

- homework/b03.md
see https://github.com/Dungeon-CampusMinden/Dungeon/pull/1506
> B03: rename Dojo-Dungeon starter

- homework/b04.md
> Homework: finalise B04

- homework/b05.md
> Homework: finalise B05

- homework/b06.md
> Homework: finalise B06

- homework/b07.md
> Homework: finalize B07

- homework/b08.md
> Homework: finalise B08

- homework/b04.md
- homework/b07.md
- homework/b09.md
> Homework: finalise B09

- lecture/building/ci.md
- lecture/coding/refactoring.md
> Lecture: finalise challenges for Rectoring lesson

- lecture/git/git-basics.md
- lecture/quality/smells.md
will be added via new tooling ...
closes #984
closes https://github.com/cagix/pandoc-lecture-zen/issues/5
> Lecture: remove remaining 'Quelle:'

- .github/workflows/tests.yaml
> Tooling: add docsify to test workflow
